phpserver:
  image: cmwn/platform-api

mysqlserver:
  image: mysql:5.5
  environment:
    MYSQL_ROOT_PASSWORD: cmwn_pass123
    MYSQL_DATABASE: cmwn_test
    MYSQL_USER: cmwn_user
    MYSQL_PASSWORD: cmwn_pass
