<?php // @codingStandardsIgnoreStart ?>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Facebook sharing information tags -->
    <meta property="og:title" content="Change My World Now">

    <title>Change My World Now</title>

    </head>
<body leftmargin="0" marginwidth="0" topmargin="0" marginheight="0" offset="0">
<center>
    <table border="0" cellpadding="0" cellspacing="0" height="100%" width="100%" style="margin:0;padding:0;height:100%!important;width:100%!important">
        <tbody><tr>
            <td align="center" valign="top">

                <table border="0" cellpadding="0" cellspacing="0" width="600" style="border:1px solid #dddddd;background-color:#fdfdfd;padding:0">
                    <tbody><tr>
                        <td align="center" valign="top">

                            <table border="0" cellpadding="0" cellspacing="0" width="600" style="background-color:#ffffff;border-bottom:0">
                                <tbody><tr>
                                    <td style="color:#202020;font-family:Arial;font-size:34px;font-weight:bold;line-height:0;padding:0;text-align:center;vertical-align:middle">


                                        <a href = "https://www.changemyworldnow.com"><img src="https://<?= $image_domain ?>/img/email/import/header_v2.png" alt="Change My World Now: A SAFE Social Media Platform for Kids" border="0" style="margin:0;padding:0;font-weight:bold;color:#01b5ff;font-size:30px;border:none;min-height:auto;line-height:100%;outline:none;text-decoration:none;text-transform:capitalize" class="CToWUd a6T" tabindex="0"></a>


                                    </td>
                                </tr>
                                </tbody></table>

                        </td>
                    </tr>
                    <tr>
                        <td align="center" valign="top">

                            <table border="0" cellpadding="10" cellspacing="0" width="450">
                                <tbody><tr>
                                    <td valign="top" style="background-color:#fdfdfd;padding:0">


                                        <table border="0" cellpadding="10" cellspacing="0" width="100%">
                                            <tbody><tr>
                                                <td valign="top" style="padding:0">
                                                    <?php echo $this->content;?>
                                                    <div style="color:#3b3b3b;font-family:Arial;font-size:17px;line-height:150%;text-align:left;border-left:30px solid #01b5ff;border-right:30px solid #01b5ff;padding:0 47.5px;min-width:440px">

                                                        <br>
                                                        <span style="text-align:center"><img src="https://<?= $image_domain ?>/img/email/import/intangibles-education.png" alt="From the intangibles to education" style="font-weight:bold;color:#01b5ff;font-size:24px;border:none;min-height:auto;line-height:100%;outline:none;text-decoration:none;text-transform:capitalize;display:inline" class="CToWUd"></span>
                                                        <table border="0" cellpadding="0" cellspacing="0" width="600" style="background-color:#fdfdfd;border-top:0;width:445px">
                                                            <tbody><tr>
                                                                <td>
                                                                    <ul style="margin-left:8px;padding-left:0">
                                                                        <li style="margin-left:8px;padding-left:0;background-repeat:no-repeat;list-style:none"><img src="https://<?= $image_domain ?>/img/email/import/empathy_environment.jpg" alt="Empathy Education and The Environment" style="border:none;font-size:14px;font-weight:bold;min-height:auto;line-height:100%;outline:none;text-decoration:none;text-transform:capitalize;display:inline" class="CToWUd"></li>
                                                                        <li style="margin-left:8px;padding-left:0;background-repeat:no-repeat;list-style:none"><img src="https://<?= $image_domain ?>/img/email/import/teamwork_energy.jpg" alt="Teamwork and Energy Sources and Uses" style="border:none;font-size:14px;font-weight:bold;min-height:auto;line-height:100%;outline:none;text-decoration:none;text-transform:capitalize;display:inline" class="CToWUd"></li>
                                                                        <li style="margin-left:8px;padding-left:0;background-repeat:no-repeat;list-style:none"><img src="https://<?= $image_domain ?>/img/email/import/leadership_stem.jpg" alt="Leadership and STEM" style="border:none;font-size:14px;font-weight:bold;min-height:auto;line-height:100%;outline:none;text-decoration:none;text-transform:capitalize;display:inline" class="CToWUd"></li>
                                                                        <li style="margin-left:8px;padding-left:0;background-repeat:no-repeat;list-style:none"><img src="https://<?= $image_domain ?>/img/email/import/mutual_waste.jpg" alt="Mutual Respect and Waste and Consumption" style="border:none;font-size:14px;font-weight:bold;min-height:auto;line-height:100%;outline:none;text-decoration:none;text-transform:capitalize;display:inline" class="CToWUd"></li>
                                                                        <li style="margin-left:8px;padding-left:0;background-repeat:no-repeat;list-style:none"><img src="https://<?= $image_domain ?>/img/email/import/citizen_animals.jpg" alt="Citizenship and The Animal Kingdom" style="border:none;font-size:14px;font-weight:bold;min-height:auto;line-height:100%;outline:none;text-decoration:none;text-transform:capitalize;display:inline" class="CToWUd"></li>
                                                                        <li style="margin-left:8px;padding-left:0;background-repeat:no-repeat;list-style:none"><img src="https://<?= $image_domain ?>/img/email/import/bullying_nutrition.jpg" alt="Ending Bullying and Health and Nutrition" style="border:none;font-size:14px;font-weight:bold;min-height:auto;line-height:100%;outline:none;text-decoration:none;text-transform:capitalize;display:inline" class="CToWUd"></li>
                                                                    </ul>
                                                                </td>
                                                            </tr>
                                                            </tbody></table>
                                                    </div>
                                                </td>
                                            </tr>
                                            </tbody></table>


                                    </td>
                                </tr>
                                </tbody></table>

                        </td>
                    </tr>
                    <tr>
                        <td align="center" valign="top">

                            <table border="0" cellpadding="10" cellspacing="0" width="600">
                                <tbody><tr>
                                    <td valign="top" style="padding-top:0">

                                        <table border="0" cellpadding="10" cellspacing="0" width="100%">
                                            <tbody><tr>
                                                <td style="padding-top:0">
                                                    <a href="https://changemyworldnow.com/terms"><img src="https://<?= $image_domain ?>/img/email/import/footer_v2.png" alt="Change My World Now is dedicated to fostering creativity and learning in all online experiences. We are committed to ensuring the safety and well-being of children of all ages. To view the complete privacy policy and terms and conditions of participation, click here." class="CToWUd a6T" tabindex="0"></a>
                                                    </a></td>
                                            </tr>
                                            </tbody></table>




                                    </td>
                                </tr>

                                <tr>

                                    <td><table border="0" cellpadding="10" cellspacing="0" width="600">
                                            <tbody><tr>
                                                <td valign="top" style="text-align:center;font-size:13px;color:#bbb;font-family:Arial;margin:0;padding:0 0 20px 0">
                                                    If you received this message in an error please do not respond.<br>
                                                    @ 2016 Change My World Now | 21 W 46th St. Suite 605, NY, NY 10036
                                                </td>
                                            </tr>
                                            </tbody></table>

                                    </td></tr>
                                </tbody></table>

                        </td>
                    </tr>
                    </tbody></table>
                <br>
            </td>
        </tr>
        </tbody></table>
</center>
</body>
</html>