<?php
/**
 * Configuration file generated by ZFTool
 * The previous configuration file is stored in application.config.old
 *
 * @see https://github.com/zendframework/ZFTool
 */
return [
    'modules' => include __DIR__ . '/modules.config.php',
    'module_listener_options' => [
        'module_paths' => [
            './module',
            './vendor',
        ],
        'config_glob_paths'        => [realpath(__DIR__) . '/autoload/{,*.}{global,local}.php'],
        'config_cache_key' => 'application.config.cache',
        'config_cache_enabled' => true,
        'module_map_cache_key' => 'application.module.cache',
        'module_map_cache_enabled' => true,
        'cache_dir' => 'data/cache/',
    ],

    'service_manager' => [
        'router' => [
            'routes' => [
                'home' => [
                    'type' => 'Literal',
                    'options' => [
                        'route'    => '/',
                        'defaults' => [
                            'controller' => 'Application\Controller\Index',
                            'action'     => 'index',
                        ],
                    ],
                ],
            ],
        ],
        'service_manager' => [
            'abstract_factories' => [
                'Zend\Cache\Service\StorageCacheAbstractServiceFactory',
                'Zend\Db\Adapter\AdapterAbstractServiceFactory',
                'Zend\Log\LoggerAbstractServiceFactory',
                'Application\Utils\AbstractTableFactory'
            ],
        ],
        'controllers' => [
            'invokables' => [
                'Application\Controller\Index' => 'Application\Controller\IndexController',
            ],
        ],
        'view_manager' => [
            'display_not_found_reason' => false,
            'display_exceptions'       => false,
            'doctype'                  => 'HTML5',
        ],
    ],
];
