<?php
/**
 * Configuration file generated by ZF Apigility Admin
 *
 * The previous config file has been stored in ./config/modules.config.old
 */
return [
    'AwsModule',
    'Application',
    'User',
    'Org',
    'Game',
    'Asset',
    'Friend',
    'Group',
    'Flip',
    'Job',
    'Import',
    'Notice',
    'AcMailer',
    'Forgot',
    'Media',
    'Skribble',
    'ZF\\ApiProblem',
    'ZF\\Configuration',
    'ZF\\Hal',
    'ZF\\ContentNegotiation',
    'ZF\\ContentValidation',
    'ZF\\Rest',
    'ZF\\Versioning',
    'Api',
    'Security',
    'Suggest',
    'SuggestCron',
];
