
<div mc:edit="std_content00">
    <span class="center"><img src="https://<?= $image_domain ?>/img/email/import/new_password.png" alt="PSST! Need a new password?" width="100%" style="font-weight:bold;color:#01b5ff;font-size:50px;padding-bottom:10px"></span><br><br>                                                        <br>
    Hey there  <?= $user['first_name']; ?>,
    <br>
    <br>
    We are here to save the day!
    <br>
    Here is your temporary password: <b><i><?= $code ?></i></b>
    <br>
    You can now log in <a href = "https://changemyworldnow.com/login"><u>here</u></a> using this password for up to 24 hours.
    <br>
    You will be required to reset your password upon log in.
    <br><br>
    Sincerely,<br>
    <em>The Change My World Now Team</em>
</div>

