<?php // @codingStandardsIgnoreStart ?>

<div style="color:#3b3b3b;font-family:Arial;font-size:17px;line-height:150%;text-align:left;border-left:30px solid #01b5ff;border-right:30px solid #01b5ff;padding:0 47.5px;min-width:440px">
    <span style="text-align:center"><img src="<?= $image_domain ?>/b58b76c3ce6ae6796a2b72284d4c41af.png" alt="PSST! Need a new password?" width="100%" style="font-weight:bold;color:#01b5ff;font-size:50px;padding-bottom:10px;border:none;min-height:auto;line-height:100%;outline:none;text-decoration:none;text-transform:capitalize;display:inline" class="CToWUd"></span><br>
    Hey there  <?= $user['first_name']; ?>,
    <br>
    <br>
    We are here to save the day!
    <br>
    Here is your temporary password: <b><i><?= $code ?></i></b><br>
    You can now log in <a href = "https://changemyworldnow.com/login"><u>here</u></a> using this password for up to 24 hours.
    <br>
    You will be required to reset your password upon log in.
    <br><br>
    Sincerely,<br>
    <em>The Change My World Now Team</em>
</div>