<h1>Congratulations!</h1>

<p>Your school was just added to Change My World Now (CMWN), an educational and safe place for kids to be online.  CMWN is a technology platform emphasizing sustainability and socially-conscious content — making learning FUN with action-based edutainment and games.</p>

<p>Access is as easy as 1-2-3…</p>

<ol>
    <li>Your school administration will provide you with an access code.</li>
    <li>Log in at this <a href="https://changemyworldnow.com/login">link</a>.</li>
    <li>Hurray, you’re in! Set up your profile and confirm your students’ accounts.</li>
</ol>

<p>We’re excited and honored to have you join us on our mission to change the world—one child at a time.</p>

<p>Sincerely,</p>
<p>The Change My World Now Team</p>