<?php // @codingStandardsIgnoreStart ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "https://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Facebook sharing information tags -->
    <meta property="og:title" content="Your school was just added to Change My World Now">

    <title>Your school was just added to Change My World Now</title>

    <style type="text/css">
        #outlook a{
            padding:0;
        }
        body{
            width:100% !important;
        }
        body{
            -webkit-text-size-adjust:none;
        }
        body{
            margin:0;
            padding:0;
        }
        img{
            border:none;
            font-size:14px;
            font-weight:bold;
            height:auto;
            line-height:100%;
            outline:none;
            text-decoration:none;
            text-transform:capitalize;
        }
        #backgroundTable{
            height:100% !important;
            margin:0;
            padding:0;
            width:100% !important;
        }
        /*
        @tab Page
        @section background color
        @tip Set the background color for your email. You may want to choose one that matches your company's branding.
        @theme page
        */
        body,.backgroundTable{
            /*@editable*/background-color:#FAFAFA;
        }
        /*
        @tab Page
        @section email border
        @tip Set the border for your email.
        */
        #templateContainer{
            /*@editable*/border:1px solid #DDDDDD;
        }
        /*
        @tab Page
        @section heading 1
        @tip Set the styling for all first-level headings in your emails. These should be the largest of your headings.
        @theme heading1
        */
        h1,.h1{
            /*@editable*/color:#01b5ff;
            display:block;
            /*@editable*/font-family:Arial;
            /*@editable*/font-size:34px;
            /*@editable*/font-weight:bold;
            /*@editable*/line-height:100%;
            margin-bottom:10px;
            /*@editable*/text-align:left;
        }
        /*
        @tab Page
        @section heading 2
        @tip Set the styling for all second-level headings in your emails.
        @theme heading2
        */
        h2,.h2{
            /*@editable*/color:#01b5ff;
            display:block;
            /*@editable*/font-family:Arial;
            /*@editable*/font-size:30px;
            /*@editable*/font-weight:bold;
            /*@editable*/line-height:100%;
            margin-bottom:10px;
            /*@editable*/text-align:left;
        }
        /*
        @tab Page
        @section heading 3
        @tip Set the styling for all third-level headings in your emails.
        @theme heading3
        */
        h3,.h3{
            /*@editable*/color:#01b5ff;
            display:block;
            /*@editable*/font-family:Arial;
            /*@editable*/font-size:26px;
            /*@editable*/font-weight:bold;
            /*@editable*/line-height:100%;
            margin-bottom:10px;
            /*@editable*/text-align:left;
        }
        /*
        @tab Page
        @section heading 4
        @tip Set the styling for all fourth-level headings in your emails. These should be the smallest of your headings.
        @theme heading4
        */
        h4,.h4{
            /*@editable*/color:#3b3b3b;
            display:block;
            /*@editable*/font-family:Arial;
            /*@editable*/font-size:20px;
            /*@editable*/font-weight:bold;
            /*@editable*/line-height:100%;
            margin-bottom:10px;
            /*@editable*/text-align:left;
        }
        /*
        @tab Header
        @section preheader style
        @tip Set the background color for your email's preheader area.
        @theme page
        */
        #templatePreheader{
            /*@editable*/background-color:#FAFAFA;
        }
        /*
        @tab Header
        @section preheader text
        @tip Set the styling for your email's preheader text. Choose a size and color that is easy to read.
        */
        .preheaderContent div{
            /*@editable*/color:#505050;
            /*@editable*/font-family:Arial;
            /*@editable*/font-size:12px;
            /*@editable*/line-height:100%;
            /*@editable*/text-align:center;
        }
        /*
        @tab Header
        @section preheader link
        @tip Set the styling for your email's preheader links. Choose a color that helps them stand out from your text.
        */
        .preheaderContent div a:link,.preheaderContent div a:visited{
            /*@editable*/color:#336699;
            /*@editable*/font-weight:normal;
            /*@editable*/text-decoration:underline;
        }
        .preheaderContent div img{
            height:auto;
            max-width:600px;
        }
        /*
        @tab Header
        @section header style
        @tip Set the background color and border for your email's header area.
        @theme header
        */
        #templateHeader{
            /*@editable*/background-color:#FFFFFF;
            /*@editable*/border-bottom:0;
        }
        /*
        @tab Header
        @section header text
        @tip Set the styling for your email's header text. Choose a size and color that is easy to read.
        */
        .headerContent{
            /*@editable*/color:#202020;
            /*@editable*/font-family:Arial;
            /*@editable*/font-size:34px;
            /*@editable*/font-weight:bold;
            /*@editable*/line-height:0;
            /*@editable*/padding:0;
            /*@editable*/text-align:center;
            /*@editable*/vertical-align:middle;
        }
        /*
        @tab Header
        @section header link
        @tip Set the styling for your email's header links. Choose a color that helps them stand out from your text.
        */
        .headerContent a:link,.headerContent a:visited{
            /*@editable*/color:#336699;
            /*@editable*/font-weight:normal;
            /*@editable*/text-decoration:underline;
        }
        #headerImage{
            height:auto;
            max-width:600px !important;
        }
        /*
        @tab Body
        @section body style
        @tip Set the background color for your email's body area.
        */
        #templateContainer,.bodyContent{
            /*@editable*/background-color:#FDFDFD;
            padding:0;
        }
        /*
        @tab Body
        @section body text
        @tip Set the styling for your email's main content text. Choose a size and color that is easy to read.
        @theme main
        */
        .bodyContent div{
            /*@editable*/color:#3b3b3b;
            /*@editable*/font-family:Arial;
            /*@editable*/font-size:17px;
            /*@editable*/line-height:150%;
            /*@editable*/text-align:left;
            border-left:30px solid #00bcff;
            border-right:30px solid #00bcff;
            padding:0 47.5px;
            min-width:440px;
            background-color:#fff;
        }
        /*
        @tab Body
        @section body link
        @tip Set the styling for your email's main content links. Choose a color that helps them stand out from your text.
        */
        .bodyContent div a:link,.bodyContent div a:visited{
            /*@editable*/color:#01b5ff;
            /*@editable*/font-weight:bold;
            /*@editable*/text-decoration:none;
        }
        .bodyContent img{
            display:inline;
        }
        /*
        @tab Footer
        @section footer style
        @tip Set the background color and top border for your email's footer area.
        @theme footer
        */
        #templateFooter{
            /*@editable*/background-color:#FDFDFD;
            /*@editable*/border-top:0;
            width:445px;
        }
        /*
        @tab Footer
        @section footer text
        @tip Set the styling for your email's footer text. Choose a size and color that is easy to read.
        @theme footer
        */
        .footerContent div{
            /*@editable*/color:#707070;
            /*@editable*/font-family:Arial;
            /*@editable*/font-size:12px;
            /*@editable*/line-height:125%;
            /*@editable*/text-align:center;
            /*@editable*/vertical-align:middle;
        }
        /*
        @tab Footer
        @section footer link
        @tip Set the styling for your email's footer links. Choose a color that helps them stand out from your text.
        */
        .footerContent div a:link,.footerContent div a:visited{
            /*@editable*/color:#336699;
            /*@editable*/font-weight:normal;
            /*@editable*/text-decoration:underline;
        }
        .footerContent{
            padding-top:0;
        }
        /*
        @tab Footer
        @section social bar style
        @tip Set the background color and border for your email's footer social bar.
        */
        #social{
            /*@editable*/background-color:#FAFAFA;
            /*@editable*/border:1px solid #F5F5F5;
        }
        /*
        @tab Footer
        @section social bar style
        @tip Set the background color and border for your email's footer social bar.
        */
        #social div{
            /*@editable*/text-align:center;
        }
        /*
        @tab Footer
        @section utility bar style
        @tip Set the background color and border for your email's footer utility bar.
        */
        #utility{
            /*@editable*/background-color:#FDFDFD;
            /*@editable*/border-top:1px solid #F5F5F5;
        }
        /*
        @tab Footer
        @section utility bar style
        @tip Set the background color and border for your email's footer utility bar.
        */
        #utility div{
            /*@editable*/text-align:center;
        }
        .center{
            text-align:center;
        }
        ol,ul,li{
            margin-left:8px;
            padding-left:0;
        }
        .bottom-bullets ul{
            margin:0;
            padding:0;
            list-style-type:none;
        }
        .bottom-bullets li{
            background-repeat:no-repeat;
            list-style:none;
            padding:0;
            margin:0;
            height:30px;
        }
        #header_mobile,#footer_mobile{
            display:none;
        }
        .footer-disclaimer{
            font-size:13px;
            color:#bbb;
            font-family:Arial;
            margin:0;
            padding:0 0 20px 0;
        }
    </style></head>
<body leftmargin="0" marginwidth="0" topmargin="0" marginheight="0" offset="0">
<center>
    <table border="0" cellpadding="0" cellspacing="0" height="100%" width="100%" id="backgroundTable">
        <tr>
            <td align="center" valign="top">
                <!-- // Begin Template Preheader \\ -->
                <table border="0" cellpadding="10" cellspacing="0" width="600" id="templatePreheader">
                    <tr>
                        <td valign="top" class="preheaderContent">

                            <!-- // Begin Module: Standard Preheader \\ -->
                            <table border="0" cellpadding="10" cellspacing="0" width="100%">
                                <tr>
                                    <td valign="top">
                                        <div mc:edit="std_preheader_content">
                                            Your school was just added to Change My World Now (CMWN),<br>an educational and safe place for kids to be online.
                                        </div>
                                    </td>
                                </tr>
                            </table>
                            <!-- // End Module: Standard Preheader \\ -->

                        </td>
                    </tr>
                </table>
                <!-- // End Template Preheader \\ -->
                <table border="0" cellpadding="0" cellspacing="0" width="600" id="templateContainer">
                    <tr>
                        <td align="center" valign="top">
                            <!-- // Begin Template Header \\ -->
                            <table border="0" cellpadding="0" cellspacing="0" width="600" id="templateHeader">
                                <tr>
                                    <td class="headerContent">

                                        <!-- // Begin Module: Standard Header Image \\ -->
                                        <a href = "https://www.changemyworldnow.com"><img id="header_desktop" src="https://<?= $image_domain ?>/img/email/import/header_v2.png" alt="Change My World Now: A SAFE Social Media Platform for Kids" style="font-weight:bold;color:#01b5ff;font-size:30px;" border="0" mc:edit="header_image"></a>
                                        <!-- // End Module: Standard Header Image \\ -->

                                    </td>
                                </tr>
                            </table>
                            <!-- // End Template Header \\ -->
                        </td>
                    </tr>
                    <tr>
                        <td align="center" valign="top">
                            <!-- // Begin Template Body \\ -->
                            <table border="0" cellpadding="10" cellspacing="0" width="450" id="templateBody">
                                <tr>
                                    <td valign="top" class="bodyContent">

                                        <!-- // Begin Module: Standard Content \\ -->
                                        <table border="0" cellpadding="10" cellspacing="0" width="100%">
                                            <tr>
                                                <td valign="top" style="padding:0;">
                                                    <div mc:edit="std_content00">
                                                        <span class="center"><img src="https://<?= $image_domain ?>/img/email/import/congratulations_text.png" alt="Congratulations!" width="100%" style="font-weight:bold;color:#01b5ff;font-size:50px;padding-bottom:10px"></span><br><br>
                                                        Your school was just added to <strong>Change My World Now</strong> (CMWN), an educational and safe place for kids to be online. CMWN is a technology platform emphasizing sustainability and socially-conscious content&mdash;making learning FUN with action-based adutainment and games.
                                                        <br>
                                                        <br>
                                                        <span class="h4">Access is as easy as 1-2-3...</span>
                                                        <ol>
                                                            <li>Your school administration will provide you with an access code.</li>
                                                            <li>Log in at this <a href="https://changemyworldnow.com/login"><i><u>link</u></i></a>.</li>
                                                            <li>Hurray, you're in! Set up your profile and confirm your students accounts.</li>
                                                        </ol>
                                                        We're excited and honored to have you join us on our mission to change the world&mdash;one child at a time.
                                                        <br><br>
                                                        Sincerely,<br>
                                                        <em>The Change My World Now Team</em>
                                                    </div>
                                                    <div class="bottom-content">

                                                        <br>
                                                        <span class="center"><img src="https://<?= $image_domain ?>/img/email/import/intangibles-education.png" alt="From the intangibles to education" style="font-weight:bold;color:#01b5ff;font-size:24px;"></span>
                                                        <table border="0" cellpadding="0" cellspacing="0" id="templateFooter" width="600">
                                                            <tr>
                                                                <td>
                                                                    <ul class="bottom-bullets">
                                                                        <li id="empathy"><img src="https://<?= $image_domain ?>/img/email/import/empathy_environment.jpg" alt="Empathy Education, The Environment"></li>
                                                                        <li id="teamwork"><img src="https://<?= $image_domain ?>/img/email/import/teamwork_energy.jpg" alt="Teamwork, Energy Sources and Uses"></li>
                                                                        <li id="leadership"><img src="https://<?= $image_domain ?>/img/email/import/leadership_stem.jpg" alt="Leadership, STEM"></li>
                                                                        <li id="mutual-respect"><img src="https://<?= $image_domain ?>/img/email/import/mutual_waste.jpg" alt="Mutual Respect, Waste and Consumption"></li>
                                                                        <li id="citizenship"><img src="https://<?= $image_domain ?>/img/email/import/citizen_animals.jpg" alt="Citizenship, The Animal Kingdom"></li>
                                                                        <li id="end-bullying"><img src="https://<?= $image_domain ?>/img/email/import/bullying_nutrition.jpg" alt="Ending Bullying, Health and Nutrition"></li>
                                                                    </ul>
                                                                </td>
                                                            </tr>
                                                        </table>
                                                    </div>
                                                </td>
                                            </tr>
                                        </table>
                                        <!-- // End Module: Standard Content \\ -->

                                    </td>
                                </tr>
                            </table>
                            <!-- // End Template Body \\ -->
                        </td>
                    </tr>
                    <tr>
                        <td align="center" valign="top">
                            <!-- // Begin Template Footer \\ -->
                            <table border="0" cellpadding="0" cellspacing="0" width="600" id="endFooter">
                                <tr>
                                    <td valign="top" class="footerContent">

                                        <table border="0" cellpadding="0" cellspacing="0" width="100%">
                                            <tr>
                                                <td style="padding-top:0;">
                                                    <a href="https://changemyworldnow.com/terms"><img id="footer_desktop" src="https://<?= $image_domain ?>/img/email/import/footer_v2.png" alt="Change My World Now is dedicated to fostering creativity and learning in all online experiences. We are committed to ensuring the safety and well-being of children of all ages. To view the complete privacy policy and terms and conditions of participation, click here." style="font-weight:bold;font-family:Arial, sans serif;color:#01b5ff;font-size:14px;">
                                                    </a></td>
                                            </tr>
                                        </table>
                                    </td>
                                </tr>

                                <tr>
                                    <!-- // Begin Template End Footer \\ -->
                                    <table border="0" cellpadding="10" cellspacing="0" width="600">
                                        <tr>
                                            <td valign="top" class="center footer-disclaimer">
                                                If you received this message in an error please do not respond.<br>
                                                @ <?= date('Y') ?> Change My World Now | 21 W 46th St. Suite 605, NY, NY 10036
                                            </td>
                                        </tr>
                                    </table>
                                    <!-- // End Template End Footer \\ -->
                                </tr>
                            </table>
                            <!-- // End Template Footer \\ -->
                        </td>
                    </tr>
                </table>
                <br>
            </td>
        </tr>
    </table>
</center>
</body>
</html>
