<h1>Import Failed!</h1>

<h4>These are the errors reported: </h4>

<ol>
<?php foreach ($errors as $errorMsg): ?>
    <li><?= $errorMsg ?></li>
<?php endforeach; ?>
</ol>

<?php if (count($warnings) > 0): ?>
<h4>The following warnings were also produced: </h4>
    <ol>
        <?php foreach ($warnings as $warnMsg): ?>
            <li><?= $warnMsg ?></li>
        <?php endforeach; ?>
    </ol>
<?php endif; ?>
