<?php // @codingStandardsIgnoreStart ?>

<div mc:edit="std_content00">
    <span class="center"><img src="https://<?= $image_domain ?>/img/email/import/congratulations_text.png" alt="Congratulations!" width="100%" style="font-weight:bold;color:#01b5ff;font-size:50px;padding-bottom:10px"></span><br><br>
    Your school was just added to <strong>Change My World Now</strong> (CMWN), an educational and safe place for kids to be online. CMWN is a technology platform emphasizing sustainability and socially-conscious content&mdash;making learning FUN with action-based adutainment and games.
    <br>
    <br>
    <span class="h4">Access is as easy as 1-2-3...</span>
    <ol>
        <li>Your school administration will provide you with an access code.</li>
        <li>Log in at this <a href="https://changemyworldnow.com/login"><i><u>link</u></i></a>.</li>
        <li>Hurray, you're in! Set up your profile and confirm your students accounts.</li>
    </ol>
    We're excited and honored to have you join us on our mission to change the world&mdash;one child at a time.
    <br><br>
    Sincerely,<br>
    <em>The Change My World Now Team</em>
</div>
