<?php // @codingStandardsIgnoreStart ?>

<div mc:edit="std_content00">
    <span class="center"><img src="https://<?= $image_domain ?>/img/email/import/congratulations_text.png" alt="Congratulations!" width="100%" style="font-weight:bold;color:#01b5ff;font-size:50px;padding-bottom:10px"></span><br><br>
    Your upload to <strong>Change My World Now</strong> was a success!
    <br>
    <br>
    <span class="h4">Access is as easy as 1-2-3...</span>
    <ol>
        <li>Share the Teacher Welcome Letter <i>(provided to you by CMWN)</i> with your faculty. <br>
            <i>* Be sure to add the unique Access Code you set for your teachers and students during the import process to the bottom of the form!</i>
        </li>
        <li>Set a goal with your teachers to have their first login be completed by a specific date.</li>
        <li>If you need to add more students, you will utilize the same process. Create a new RIBR Report, add it to your school spreadsheet and upload the updated spreadsheet. It will not create duplicate accounts, only the new students will be added. </li>
        <li>Contact the customer support team at <font color='#01b5ff'>  646.861.0571</font> if you need help at anytime. Hours: 9am - 7pm EST.</li>
    </ol>
    <br>
    Sincerely,<br>
    <em>The Change My World Now Team</em>
</div>
