<?php // @codingStandardsIgnoreStart ?>

<div style="color:#3b3b3b;font-family:Arial;font-size:17px;line-height:150%;text-align:left;border-left:30px solid #01b5ff;border-right:30px solid #01b5ff;padding:0 47.5px;min-width:440px">
    <span style="text-align:center"><img src="https://<?= $image_domain ?>/img/email/import/congratulations_text.png" alt="Congratulations!" width="100%" style="font-weight:bold;color:#01b5ff;font-size:50px;padding-bottom:10px;border:none;min-height:auto;line-height:100%;outline:none;text-decoration:none;text-transform:capitalize;display:inline" class="CToWUd"></span><br>
    Your upload to <strong>Change My World Now</strong> was a success!
    <br>
    <br>
    <span style="color:#3b3b3b;display:block;font-family:Arial;font-size:20px;font-weight:bold;line-height:100%;margin-bottom:10px;text-align:left">Access is as easy as 1-2-3...</span>
    <ol style="margin-left:8px;padding-left:0">
        <li style="margin-left:8px;padding-left:0;margin-bottom:20px">Share the Teacher Welcome Letter <i>(provided to you by CMWN)</i> with your faculty. <br>
            <i>  Be sure to add the unique Access Code you set for your teachers and students during the import process to the bottom of the form!</i>
        </li>
        <li style="margin-left:8px;padding-left:0;margin-bottom:20px">Set a goal with your teachers to have their first login be completed by a specific date.</li>
        <li style="margin-left:8px;padding-left:0;margin-bottom:20px">If you need to add more students, you will utilize the same process. Create a new RIBR Report, add it to your school spreadsheet and upload the updated spreadsheet. It will not create duplicate accounts, only the new students will be added. </li>
        <li style="margin-left:8px;padding-left:0;margin-bottom:20px">Contact the customer support team at <font color='#01b5ff'>  646.861.0571</font> if you need help at anytime. Hours: 9am - 7pm EST.</li>
    </ol>
    <br>
    Sincerely,<br>
    <em>The Change My World Now Team</em>
</div>