<?php // @codingStandardsIgnoreStart ?>

<div style="color:#3b3b3b;font-family:Arial;font-size:17px;line-height:150%;text-align:left;border-left:30px solid #01b5ff;border-right:30px solid #01b5ff;padding:0 47.5px;min-width:440px">
    <span style="text-align:center"><img src="https://<?= $image_domain ?>/1c50e91ae766df8e7a50be3dfcf0299a.png" alt="Dont Worry!" width="100%" style="font-weight:bold;color:#01b5ff;font-size:50px;padding-bottom:10px;border:none;min-height:auto;line-height:100%;outline:none;text-decoration:none;text-transform:capitalize;display:inline" class="CToWUd"></span><br>
    <br>
    Your upload to <strong>Change My World Now</strong> could not go through because of an error on our end.
    <br>
    We are addressing the problem, and will get back to you shortly. <br>
    Thank you for your patience!
    <br>
    <br>
    Sincerely,<br>
    <em>The Change My World Now Team</em>
</div>