<?php
// do not overwrite this with a local file.
// Currently the PHINX seeder is not executed through
// zf2.  The seeder is looking for this file.
// Any local files will be not be seeded into the db
return [
    'user-names' => [
        'left' => [
            'active',
            'adorable',
            'amazing',
            'awesome',
            'beautiful',
            'bold',
            'bouncing',
            'brave',
            'bright',
//            'brilliant', REMOVED CORE-2180
            'bronze',
            'calm',
            'caring',
            'champion',
            'charming',
            'cheerful',
            'chic',
            'clever',
            'confident',
            'cool',
            'creative',
            'curious',
            'cute',
            'daring',
//            'dedicated', REMOVED CORE-2180
//            'delightful', REMOVED CORE-2180
            'energetic',
            'epic',
            'fabulous',
            'fancy',
            'fantastic',
            'fast',
            'flashy',
            'friendly',
            'fun',
            'funny',
            'generous',
            'genuine',
            'gold',
            'good',
            'graceful',
            'great',
            'green',
            'groovy',
            'happy',
            'helpful',
            'hip',
            'honest',
//            'inspiring', REMOVED CORE-2180
            'jazzy',
            'jolly',
            'joyful',
            'joyous',
            'kind',
            'lively',
            'loving',
            'loyal',
            'lucky',
            'magical',
            'merry',
            'mighty',
            'neat',
            'nice',
            'nifty',
            'noble',
            'orange',
            'original',
            'playful',
//            'pleasant', REMOVED CORE-2180
            'positive',
//            'precious', REMOVED CORE-2180 (and when Frodo threw it into Mordo)
            'proud',
            'purple',
            'rare',
//            'reliable', REMOVED CORE-2180
            'royal',
            'silly',
            'silver',
            'smart',
            'smiley',
            'smiling',
            'solar',
            'sonic',
            'soulful',
            'stellar',
            'strong',
            'studious',
            'sunny',
            'super',
            'sweet',
            'swift',
            'talented',
            'unique',
            'upbeat',
            'wise',
            'witty',
            'zany',
        ],
        'right' => [
            'albatross',
//            'alligator', REMOVED CORE-2180
            'angelfish',
            'antelope',
//            'armadillo', REMOVED CORE-2180
            'badger',
//            'barracuda', REMOVED CORE-2180
            'bear',
            'bee',
            'beetle',
            'bison',
            'bluebird',
            'bluefish',
            'bluejay',
            'bobcat',
            'buffalo',
            'bulldog',
            'butterfly',
            'cardinal',
            'caribou',
//            'caterpillar', REMOVED CORE-2180
            'chameleon',
            'cheetah',
//            'chinchilla', REMOVED CORE-2180
            'chipmunk',
            'coyote',
            'crane',
//            'crocodile', REMOVED CORE-2180
            'deer',
            'dolphin',
            'dragon',
            'dragonfly',
            'eagle',
            'emu',
            'falcon',
            'fish',
            'flamingo',
            'fox',
            'frog',
            'gazelle',
            'gecko',
            'gibbon',
            'giraffe',
            'goose',
            'guppy',
            'hamster',
            'hawk',
            'hedgehog',
            'heron',
            'horse',
            'hound',
            'iguana',
            'impala',
            'jaguar',
            'jellyfish',
            'kangaroo',
            'kingfisher',
            'koala',
            'lemur',
            'leopard',
            'lion',
            'lionfish',
            'lizard',
            'lynx',
            'mantaray',
            'meerkat',
            'mongoose',
            'moose',
            'narwhal',
            'orca',
            'osprey',
            'ostrich',
            'otter',
            'owl',
            'panda',
            'panther',
            'parakeet',
            'parrot',
            'pelican',
            'penguin',
            'puffin',
            'puma',
            'rabbit',
            'reindeer',
            'roadrunner',
            'robin',
            'seahorse',
            'seal',
            'sealion',
            'shark',
            'sparrow',
            'starfish',
            'stingray',
            'sunfish',
            'swan',
            'terrier',
            'tiger',
            'tortoise',
            'toucan',
            'turtle',
            'wallaby',
            'wolf',
            'zebra',
        ]
    ]
];
