<?php
// do not overwrite this with a local file.
// Currently the PHINX seeder is not executed through
// zf2.  The seeder is looking for this file.
// Any local files will be not be seeded into the db
return [
    'user-names' => [
        'left' => [
            'admiring',
            'adoring',
            'amazing',
            'awesome',
            'big',
            'clever',
            'cranky',
            'crazy',
            'determined',
            'dreamy',
            'drunk',
            'elated',
            'elegant',
            'evil',
            'fervent',
            'focused',
            'goofy',
            'happy',
            'huge',
            'high',
            'hopeful',
            'hungry',
            'jolly',
            'jovial',
            'loving',
            'large',
            'modest',
            'naughty',
            'pensive',
            'prickly',
            'reverent',
            'sharp',
            'sick',
            'silly',
            'sleepy',
            'small',
            'tender',
            'thirsty',
            'tiny',
            'trusting'
        ],
        'right' => [
            'raccoon',
            'llama',
            'goat',
            'opossums',
            'skunk',
            'horse',
            'lion',
            'duck',
            'deer',
            'gorilla',
            'beaver',
            'chipmunk',
            'turtle',
            'chinchilla',
            'chick',
            'sloth',
            'wombat',
            'sheep',
            'bunny',
            'kangaroo',
            'cow',
            'squirrel',
            'hedgehog',
            'seal',
            'bear',
            'penguin',
            'koala',
            'fox',
            'puppy',
            'giraffe',
            'elephant',
            'piglet',
            'panda',
            'kitten',
            'otter'
        ]
    ]
];
