<?php
// @codingStandardsIgnoreStart

return [
    'games' => [
        'master' => [
            'polar-bear'      => [
                'game_id'     => 'polar-bear',
                'title'       => 'Polar Bear',
                'description' => 'The magnificent Polar Bear is in danger of becoming extinct. Get the scoop and go offline for the science on how they stay warm!',
                'coming_soon' => 0,
                'meta'        => '{"desktop" : false, "unity" : false}',
            ],
            'sea-turtle'      => [
                'game_id'     => 'sea-turtle',
                'title'       => 'Sea Turtle',
                'description' => 'Sea Turtles are amazing creatures with a lot to teach us! Get cool turtle facts, play games and find out why they are endangered.',
                'coming_soon' => 0,
                'meta'        => '{"desktop" : false, "unity" : false}',
            ],
            'animal-id'       => [
                'game_id'     => 'animal-id',
                'title'       => 'Animal ID',
                'description' => 'Can you ID the different kinds of animals? Do you know what plants and animals belong together? Prove it and learn it right here!',
                'coming_soon' => 0,
                'meta'        => '{"desktop" : false, "unity" : false}',
            ],
            'litter-bug'      => [
                'game_id'     => 'litter-bug',
                'title'       => 'Litterbug',
                'description' => 'Sing it strong! Learn a great sing-a-long song while you work to save the environment! Doesn\'t get better!',
                'coming_soon' => 0,
                'meta'        => '{"desktop" : false, "unity" : false}',
            ],
            'be-bright'       => [
                'game_id'     => 'be-bright',
                'title'       => 'Be Bright',
                'description' => 'Become a Light Saver agent of change! This music video will kick your inner superhero into high gear!',
                'coming_soon' => 0,
                'meta'        => '{"desktop" : false, "unity" : false}',
            ],
            'fire'            => [
                'game_id'     => 'fire',
                'title'       => 'FIRE!!!',
                'description' => 'All about firefighters and firefighting theory. These are true heroes among us - maybe you will be one someday?',
                'coming_soon' => 0,
                'meta'        => '{"desktop" : false, "unity" : false}',
            ],
            'drought-out'     => [
                'game_id'     => 'drought-out',
                'title'       => 'DroughtOUT',
                'description' => 'We all depend on water for life! What happens when there is a drought? And what you can do offline to help conserve water?',
                'coming_soon' => 0,
                'meta'        => '{"desktop" : false, "unity" : false}',
            ],
            'twirl-n-swirl'   => [
                'game_id'     => 'twirl-n-swirl',
                'title'       => 'Twirl n\' Swirl',
                'description' => 'Ever wonder where things go when you flush? It’s not as simple as you think! Learn how you can help the environment—and avoid the plunger!',
                'coming_soon' => 0,
                'meta'        => '{"desktop" : false, "unity" : false}',
            ],
            'meerkat-mania'   => [
                'game_id'     => 'meerkat-mania',
                'title'       => 'Meerkat Mania',
                'description' => 'These Meerkats, from the deserts and grasslands of Africa, have a lot to say about friendship! Check out their funny video, learn the \'Meerkat Move,\' and more!',
                'coming_soon' => 0,
                'meta'        => '{"desktop" : false, "unity" : false}',
            ],
            'printmaster'     => [
                'game_id'     => 'printmaster',
                'title'       => 'Printmaster',
                'description' => 'Become a junior crimefighter by recognizing the different types of fingerprints! Take your knowledge offline and dust for fingerprints at home.',
                'coming_soon' => 0,
                'meta'        => '{"desktop" : false, "unity" : false}',
            ],
            'happy-fish-face' => [
                'game_id'     => 'happy-fish-face',
                'title'       => 'Happy Fish Face',
                'description' => 'Find out how a fish feels! Get the scoop on water pollution and have fun doing it! Grab a net - we\'re cleaning up!',
                'coming_soon' => 0,
                'meta'        => '{"desktop" : false, "unity" : false}',
            ],
            'pedal-pusher'    => [
                'game_id'     => 'pedal-pusher',
                'title'       => 'Pedal Pusher',
                'description' => 'Jump, flip and win points! Guide your bike through the terrain.',
                'coming_soon' => 0,
                'meta'        => '{"desktop" : true, "unity" : true}',
            ],
            'salad-rain'      => [
                'game_id'     => 'salad-rain',
                'title'       => 'Salad Rain',
                'description' => 'Be a Salad Chef!  Make tasty salads by following the recipes!',
                'coming_soon' => 0,
                'meta'        => '{"desktop" : true, "unity" : true}',
            ],
            'turtle-hurdle'   => [
                'game_id'     => 'turtle-hurdle',
                'title'       => 'Turtle Hurdle',
                'description' => 'Sea Turtles are at risk but you will guide yours to safety!',
                'coming_soon' => 0,
                'meta'        => '{"desktop" : true, "unity" : true}',
            ],
            'twirling-tower'  => [
                'game_id'     => 'twirling-tower',
                'title'       => 'Twirling Tower',
                'description' => 'Weather can change at any moment! Stay ahead of the tornado!',
                'coming_soon' => 0,
                'meta'        => '{"desktop" : true, "unity" : true}',
            ],
            'bloom-boom'      => [
                'game_id'     => 'bloom-boom',
                'title'       => 'Bloom Boom',
                'description' => 'Be a pollinating pilot! Direct your pollinators to get a field of flowers!',
                'coming_soon' => 0,
                'meta'        => '{"desktop" : true, "unity" : true}',
            ],
            'carbon-catcher'  => [
                'game_id'     => 'carbon-catcher',
                'title'       => 'Carbon Catcher',
                'description' => 'Bubble, bubble, carbon is trouble! Clean up the air by converting emissions!',
                'coming_soon' => 0,
                'meta'        => '{"desktop" : true, "unity" : true}',
            ],
            'waterdrop'       => [
                'game_id'     => 'waterdrop',
                'title'       => 'Waterdrop',
                'description' => 'Drip, drip drop! Water conservation is critical. Harness the power and score big!',
                'coming_soon' => 0,
                'meta'        => '{"desktop" : true, "unity" : true}',
            ],
            'reef-builder'    => [
                'game_id'     => 'reef-builder',
                'title'       => 'Reef Builder',
                'description' => 'Create an ocean reef habitat for sea creatures and win big doing it!',
                'coming_soon' => 0,
                'meta'        => '{"desktop" : true, "unity" : true}',
            ],
            'monarch'         => [
                'game_id'     => 'monarch',
                'title'       => 'Monarchs',
                'description' => 'Monarch Butterflies are crucial for the environment yet they are endangered! This is your spot!',
                'coming_soon' => 0,
                'meta'        => '{"desktop" : false, "unity" : false}',
            ],
            'tag-it'          => [
                'game_id'     => 'tag-it',
                'title'       => 'Tag It',
                'description' => 'TAG IT! makes water conservation fun with a cool art project!',
                'coming_soon' => 0,
                'meta'        => '{"desktop" : false, "unity" : false}',
            ],
            'skribble'        => [
                'game_id'     => 'skribble',
                'title'       => 'Skribble',
                'description' => 'Skribble is the fun and creative way to message your classmates and brighten someone\'s day!',
                'coming_soon' => 0,
                'meta'        => '{"desktop" : false, "unity" : false}',
            ],
        ],
    ],
];
